#ubuntu pod deployment

apiVersion: v1
kind: Pod
metadata:
  name: pod-ub1
  labels:
    pod: pod-ub1
spec:
  containers:
  - name: ub-basic
    image: johntmoy13/ub-basic:with_web_server
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: service-ub1
  labels:
    service: service-ub1
spec:
  type: NodePort
  ports:
  - name: port80
    port: 80
    nodePort: 30080
  - name: port22
    port: 22
    nodePort: 30022  
  selector:
    pod: pod-ub1
